# Database
spring.datasource.url=jdbc:postgresql://dpg-d8ne3qnlk1mc73915540-a.singapore-postgres.render.com/teamsync_mqid
spring.datasource.username=teamsync_user
spring.datasource.password=q9YoEqT3GJ9hikudzt1M2vYpq5x8PTAl
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=${PORT:8080}

# JWT
app.jwt.secret=${JWT_SECRET:teamsync_super_secret_jwt_key_2024}
app.jwt.expiration=86400000